function onEachFeature(feature, layer) {
  if (feature.properties) {
  var html = feature.properties.Name + "<br>" + feature.properties.Caption +
  '<a href="' + feature.properties.URL + '"><img src="'+ feature.properties.Thumb_URL+ '"></a>';  
  layer.bindPopup(html);
  }
}

var map = L.map('map').setView([34.07, -117.2], 13);

L.tileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
  attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
}).addTo(map);

geojsonFeature = {
  			"type": "FeatureCollection",
  			"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
  			"features": [
    		{ "type": "Feature", "properties": { "Name": "Welcome to the City of Redlands", "Caption": "Located about 60 miles east of Los Angeles, replete with cultural, artistic and historical sites. Redlands, emerging as a regional leader, boasts small-town charm, and features a world center of geospatial information technologies.  (<i><a href=\"http:\/\/en.wikipedia.org\/wiki\/Redlands,_California\" target=\"_blank\">More info<\/a><\/i>)", "Icon_color": "R", "Long": -117.182421, "Lat": 34.055448, "URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/Cover.JPG", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/cover.png" }, "geometry": { "type": "Point", "coordinates": [ -117.182421, 34.055448 ] } }, 
    		{ "type": "Feature", "properties": { "Name": "Esri", "Caption": "Headquartered in Redlands, Esri is a world leader in GIS software. Founded by Jack and Laura Dangermond in 1969, Esri now has 10 regional offices in the U.S. and a network of 80 international distributors, with about a million users in 200 countries. (<i><a href=\"http:\/\/www.esri.com\" target=\"_blank\">Website<\/a><\/i>)", "Icon_color": "R", "Long": -117.195688, "Lat": 34.056932, "URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/Esri.JPG", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/esri.png" }, "geometry": { "type": "Point", "coordinates": [ -117.195688, 34.056932 ] } },
    		{ "type": "Feature", "properties": { "Name": "Redlands Bowl", "Caption": "Built in 1930, the Redlands Bowl Procellis features free summer concerts on Tuesday and Friday evenings from late June through August. More than 100,000 guests enjoy this Redlands tradition each year.  <i><a href=\"http:\/\/www.redlandsbowl.com\/\" target=\"_blank\">the theater website<\/a><\/i>", "Icon_color": "R", "Long": -117.184922, "Lat": 34.053552, "URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/Redlands_bowl.JPG", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/redlands_bowl.png" }, "geometry": { "type": "Point", "coordinates": [ -117.184922, 34.053552 ] } },
    		{ "type": "Feature", "properties": { "Name": "University of Redlands", "Caption": "The 160-acre University, founded in 1907, is a highly ranked liberal arts university that includes Schools of Music, Business, and Education. It is home to the Redlands Symphony Orchestra, and annually presents over 200 music, arts, theatre, dance, and other cultural events.", "Icon_color": "R", "Long": -117.165481, "Lat": 34.061758, "URL": "http:\/\/www.youtube.com\/embed\/epRY3eZLQSc#isVideo", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/redlands_university_v.png" }, "geometry": { "type": "Point", "coordinates": [ -117.165481, 34.061758 ] } },
   	 		{ "type": "Feature", "properties": { "Name": "Lincoln Memorial Shrine", "Caption": "The Lincoln Memorial Shrine, the only museum dedicated to Abraham Lincoln west of the Mississippi River, was designed by noted Southern California architect Elmer Grey and donated to the City of Redlands by Robert Watchorn in 1932. The construction of reinforced concrete is faced with Bedford Indiana limestone plates, upon which are inscribed excerpts from Lincoln's speeches.", "Icon_color": "R", "Long": -117.183519, "Lat": 34.053799, "URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/Lincoln_shrine.JPG", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/lincoln.png" }, "geometry": { "type": "Point", "coordinates": [ -117.183519, 34.053799 ] } },
    		{ "type": "Feature", "properties": { "Name": "Smiley Library", "Caption": "The Moorish-style Smiley Library was constructed in 1898 by early Redlands benefactor Albert Smiley as a gift to the people of Redlands. Located in Smiley Park, it is a California Historic Landmark and is listed on the National Register of Historic Places.", "Icon_color": "R", "Long": -117.184012, "Lat": 34.054459, "URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/AK_Smiley_library.JPG", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/library.png" }, "geometry": { "type": "Point", "coordinates": [ -117.184012, 34.054459 ] } },
    		{ "type": "Feature", "properties": { "Name": "Brookside Post Office", "Caption": "This Mission Revival-style structure was built by WPA craftsmen in the 1934 and is on the National Register of Historic Places. It includes a small museum featuring items of historic postal significance, both locally and nationally.", "Icon_color": "R", "Long": -117.185691, "Lat": 34.055174, "URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/post_office.JPG", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/post_office.png" }, "geometry": { "type": "Point", "coordinates": [ -117.185691, 34.055174 ] } },
    		{ "type": "Feature", "properties": { "Name": "San Bernardino County Museum", "Caption": "The San Bernardino County Museum features displays of pioneer life, Indian relics, minerals and fossils, ornithology, anthropology, archaeology, earth science, natural history, and paleontology. More info at <i><a href=\"http:\/\/www.co.san-bernardino.ca.us\/museum\/\" target=\"_blank\">the museum website<\/a><\/i>", "Icon_color": "R", "Long": -117.222980, "Lat": 34.068535, "URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/Museum.jpg", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/museum.png" }, "geometry": { "type": "Point", "coordinates": [ -117.22298, 34.068535 ] } },
    		{ "type": "Feature", "properties": { "Name": "Pharaoh's Adventure Park", "Caption": "Pharaoh's Adventure Park (formerly Pharaoh's Lost Kingdom), is a 20-acre family entertainment complex that offers attractions like Splash Kingdom Water Park, miniature golf, go-kart tracks, and SkyTown jumping activities. More info at <i><a href=\"http:\/\/splashkingdom.net\/\" target=\"_blank\">the museum website<\/a><\/i>", "Icon_color": "R", "Long": -117.226887, "Lat": 34.068046, "URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/Pharaohs.jpg", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/Pharaohs.png" }, "geometry": { "type": "Point", "coordinates": [ -117.226887, 34.068046 ] } },
    		{ "type": "Feature", "properties": { "Name": "Citrus Plaza", "Caption": "Citrus Plaza is a regional shopping center located near I-10 and I-210 in Redlands, California. A central location in a growing trade area and an outstanding mix of prominent national retail tenants makes it a popular shopping destination.", "Icon_color": "R", "Long": -117.204880, "Lat": 34.072526, "URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/Citrus_Plaza.jpg", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/Citrus_Plaza.png" }, "geometry": { "type": "Point", "coordinates": [ -117.20488, 34.072526 ] } },
    		{ "type": "Feature", "properties": { "Name": "Krikorian Premiere Theatres", "Caption": "See movie information and show times at <i><a href=\"http:\/\/www.kptmovies.com\/\" target=\"_blank\">the theater website<\/a><\/i>", "Icon_color": "R", "Long": -117.185380, "Lat": 34.058519, "URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/Krikorian.jpg", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/Krikorian.png" }, "geometry": { "type": "Point", "coordinates": [ -117.18538, 34.058519 ] } },
    		{ "type": "Feature", "properties": { "Name": "Market Night", "Caption": "Every Thursdays from 6pm to 9pm. This is one of the most successful certified farmers markets in Southern California. Visitors are pleasantly surrounded by an inviting atmosphere complete with hundreds of food and merchandise booths, lighted trees, and great musical entertainment.", "Icon_color": "R", "Long": -117.182587, "Lat": 34.056432, "URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/Night_Market.JPG", "Thumb_URL": "http:\/\/esrimapbook.esri.com\/GTKwebgis\/chapter1\/thumbnails\/Night_Market.png" }, "geometry": { "type": "Point", "coordinates": [ -117.182587, 34.056432 ] } }
  		  ]
};
    
L.geoJson(geojsonFeature, {
	onEachFeature: onEachFeature
}).addTo(map);

